// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVaNyOR1TvW_WNZCdEVWe6NMpkrGtDc7g',
    appId: '1:256487422031:web:63895e6c760c0a0fbc923a',
    messagingSenderId: '256487422031',
    projectId: 'sketchshare-47875',
    authDomain: 'sketchshare-47875.firebaseapp.com',
    storageBucket: 'sketchshare-47875.firebasestorage.app',
    measurementId: 'G-BP1K0PS9CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNcX04YzbisZH0yBNxZ1MnDCchw4QEOE',
    appId: '1:256487422031:android:be6db80095605586bc923a',
    messagingSenderId: '256487422031',
    projectId: 'sketchshare-47875',
    storageBucket: 'sketchshare-47875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOcgvfrileBQXXx3Wc9U4fh99VGJf8Zws',
    appId: '1:256487422031:ios:86ad505a30bed9a5bc923a',
    messagingSenderId: '256487422031',
    projectId: 'sketchshare-47875',
    storageBucket: 'sketchshare-47875.firebasestorage.app',
    androidClientId: '256487422031-fg7ltuqfkm1ip8ahbebdsiea4e59sdq2.apps.googleusercontent.com',
    iosClientId: '256487422031-ar4u1jgkusub5n38qlq9dl0hvntqajug.apps.googleusercontent.com',
    iosBundleId: 'com.example.sketchshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOcgvfrileBQXXx3Wc9U4fh99VGJf8Zws',
    appId: '1:256487422031:ios:86ad505a30bed9a5bc923a',
    messagingSenderId: '256487422031',
    projectId: 'sketchshare-47875',
    storageBucket: 'sketchshare-47875.firebasestorage.app',
    androidClientId: '256487422031-fg7ltuqfkm1ip8ahbebdsiea4e59sdq2.apps.googleusercontent.com',
    iosClientId: '256487422031-ar4u1jgkusub5n38qlq9dl0hvntqajug.apps.googleusercontent.com',
    iosBundleId: 'com.example.sketchshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVaNyOR1TvW_WNZCdEVWe6NMpkrGtDc7g',
    appId: '1:256487422031:web:aca54aebc3a69296bc923a',
    messagingSenderId: '256487422031',
    projectId: 'sketchshare-47875',
    authDomain: 'sketchshare-47875.firebaseapp.com',
    storageBucket: 'sketchshare-47875.firebasestorage.app',
    measurementId: 'G-YFQ5J4XBN2',
  );

}